# Generated by Django 3.2.9 on 2022-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('addr', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=6)),
                ('detail_addr', models.CharField(blank=True, max_length=128)),
                ('busi_num', models.CharField(max_length=10)),
                ('busi_num_img', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
