# Generated by Django 3.2.9 on 2022-03-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('addr', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=6)),
                ('detail_addr', models.CharField(blank=True, max_length=128)),
                ('busi_num', models.CharField(max_length=10)),
                ('busi_num_img', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
