# Generated by Django 3.2.9 on 2022-06-16 01:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_img',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), null=True, size=3),
        ),
    ]
