# Generated by Django 3.2.9 on 2022-04-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=24, verbose_name='편의시설 이름')),
                ('category', models.CharField(choices=[('CAFE', 'CAFE'), ('COFFEE', 'COFFEE'), ('CONVEIENCE', 'CONVEIENCE'), ('NOODLE', 'NOODLE'), ('BREAD', 'BREAD'), ('BEVERAGE', 'BEVERAGE')], max_length=15, verbose_name='편의시설 카테고리')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'facility',
                'db_table': 'facility',
            },
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': 'store'},
        ),
    ]
