# Generated by Django 3.2.9 on 2022-03-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': 'store'},
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=24)),
                ('deleted', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='store.store')),
            ],
            options={
                'verbose_name_plural': 'facility',
                'db_table': 'facility',
            },
        ),
    ]
