# Generated by Django 3.2.9 on 2022-04-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220403_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='category',
            field=models.CharField(choices=[('CAFE', '카페'), ('COFFEE', '커피'), ('CONVEIENCE', '편의점'), ('NOODEL', '면'), ('BREAD', '빵'), ('BEVERAGE', '음료')], default='', max_length=15, verbose_name='편의시설 카테고리'),
        ),
        migrations.CreateModel(
            name='JoinFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_facility', to='store.facility', verbose_name='편의시설')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_facility', to='store.store', verbose_name='업체')),
            ],
            options={
                'verbose_name_plural': 'join_facility',
                'db_table': 'join_facility',
            },
        ),
    ]
