# Generated by Django 3.2.9 on 2022-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_joinfacility_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='busi_num_img',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
