# Generated by Django 3.2.9 on 2022-04-25 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_store_busi_num_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="price",
        ),
        migrations.AddField(
            model_name="store",
            name="price",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default=dict),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
