version: "3"

services:
  api_server:
    image: tpdnrzz/good-cafeteria
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.prod
    container_name: api_server
    ports:
      - "8000:8000"
    volumes:
      - ~/.aws/:/root/.aws:ro #Ro: Read only option