version: "3"

services:
  db:
    image: postgres
    container_name: db_server
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=good_cafeteria
    ports:
      - "5432:5432"
    volumes:
      - ~/Dev/backend_db:/var/lib/postgresql/data/
