# Generated by Django 3.2.9 on 2022-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=12)),
                ('auth_num', models.CharField(max_length=6)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'phone_auth_log',
            },
        ),
    ]
