# Generated by Django 3.2.9 on 2022-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=12, verbose_name='휴대폰 번호')),
                ('auth_num', models.CharField(max_length=6, verbose_name='인증번호')),
                ('confirmed', models.BooleanField(default=False, verbose_name='인증 여부')),
                ('purpose', models.CharField(choices=[('AUTH', 'AUTH'), ('PASSWORD', 'PASSWORD')], max_length=8, verbose_name='인증 목적')),
            ],
            options={
                'db_table': 'phone_auth_log',
            },
        ),
    ]
