# Generated by Django 3.2.9 on 2022-05-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('view', models.BooleanField(verbose_name='공개 여부')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
            ],
            options={
                'verbose_name_plural': 'notice',
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='NoticeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('view', models.BooleanField(verbose_name='공개 여부')),
                ('deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
            ],
            options={
                'verbose_name_plural': 'notice_admin',
                'db_table': 'notice_admin',
            },
        ),
    ]
