# Generated by Django 3.2.9 on 2022-05-31 00:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('menus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=10)),
                ('provide_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'menu',
                'db_table': 'menu',
            },
        ),
    ]
