# Generated by Django 3.2.9 on 2022-04-20 14:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0006_alter_joinfacility_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('menus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='store.store', verbose_name='업체')),
            ],
            options={
                'verbose_name_plural': 'menu',
                'db_table': 'menu',
            },
        ),
    ]
